name: Headless
version: '${project.version}'
main: uk.sleepylux.headlessplugin.HeadlessPlugin
api-version: '1.20'
commands:
  hcredits:
    description: Get the plugin credits
    usage: /credits
  hrevive:
    description: Revive a user
    usage: /revive
  hgetHead:
    description: Get a players head
    usage: /getHead <Playername>